apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mysql-redmine.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: redmine
  name: redmine
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redmine
    spec:
      containers:
      - env:
        - name: DB_ADAPTER
          value: mysql2
        - name: DB_HOST
          value: mysql-service
        - name: DB_NAME
          value: redmine_production
        - name: DB_PASS
          value: password
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: redmine
        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_INTERVAL
          value: "30"
        - name: IMAP_PASS
          value: password
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_USER
          value: mailer@example.com
        - name: REDMINE_BACKUP_EXPIRY
        - name: REDMINE_BACKUP_SCHEDULE
        - name: REDMINE_BACKUP_TIME
        - name: REDMINE_CONCURRENT_UPLOADS
          value: "2"
        - name: REDMINE_HTTPS
          value: "false"
        - name: REDMINE_PORT
          value: "10083"
        - name: REDMINE_RELATIVE_URL_ROOT
        - name: REDMINE_SECRET_TOKEN
        - name: REDMINE_SUDO_MODE_ENABLED
          value: "false"
        - name: REDMINE_SUDO_MODE_TIMEOUT
          value: "15"
        - name: SMTP_AUTHENTICATION
          value: :login
        - name: SMTP_DOMAIN
          value: www.example.com
        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_METHOD
          value: smtp
        - name: SMTP_PASS
          value: password
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_USER
          value: mailer@example.com
        - name: TZ
          value: Asia/Kolkata
#        image: sameersbn/redmine:3.4.6
        image: atjapan2015/redmine:3.4.8
        name: redmine
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /home/redmine/data
          name: redmine-claim0
      restartPolicy: Always
      volumes:
      - name: redmine-claim0
        hostPath:
          path: /srv/docker/redmine/redmine
#        persistentVolumeClaim:
#          claimName: redmine-claim0
status: {}
